# This workflow runs on every push and checks whether everything looks good

name: Quick check

on:
  push:
    tags:
      - "!v*"
    branches:
      - "*"
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  quick_check:
    env:
      CARGO_TERM_COLOR: always
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Rust Nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: clippy, rustfmt

      - name: Install Rust Stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install Rust tooling
        uses: taiki-e/install-action@v1
        with:
          tool: nextest

      - name: Cache Dependencies & Build Outputs
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Check out our project
        uses: actions/checkout@v3

      - name: Cargo fmt
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: fmt
          args: --all -- --check

      - name: Cargo clippy
        uses: actions-rs/cargo@v1
        with:
          toolchain: nightly
          command: clippy
          args: --tests -- -D warnings

      - name: Check out the Polkadot Repo
        uses: actions/checkout@v3
        with:
          repository: paritytech/polkadot-sdk
          ref: master
          path: polkadot

      - name: Debug
        run: |
          pwd
          ls -al

      - name: Cargo nextest
        uses: actions-rs/cargo@v1
        env:
          REPO_POLKADOT: /home/runner/work/submig/submig/polkadot-sdk
        with:
          command: nextest
          args: run

      - name: Cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
